; ---------------------------------------------------------------------------
; vic-ii_colors.inc - Color Definitions for the VIC-II
; Digital Rain on the Commodore 64
;

.ifndef ::COLORS_INC_
::COLORS_INC = 1

VIC_BLACK           = $0
VIC_WHITE           = $1
VIC_RED             = $2
VIC_CYAN            = $3
VIC_PURPLE          = $4
VIC_GREEN           = $5
VIC_BLUE            = $6
VIC_YELLOW          = $7
VIC_ORANGE          = $8
VIC_BROWN           = $9
VIC_PINK            = $A
VIC_DARK_GRAY       = $B
VIC_GRAY            = $C
VIC_LIGHT_GREEN     = $D
VIC_LIGHT_BLUE      = $E
VIC_LIGHT_GRAY      = $F

.endif