; ---------------------------------------------------------------------------
; screen.inc - Screen Management Declarations
; Digital Rain on the Commodore VIC-20
;

.ifndef ::SCREEN_INC_
::SCREEN_INC_ = 1

.import init_video
.import wait_for_frame
; .import init_pointers
; .import detect_video_type
; .import clear_color_ram
; .import clear_screen
; .import copy_chars
; .import patch_char
; .import enable_ram_fonts

.endif